import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Steam Clone App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        {/* <div> Your nav bar area</div> */}
        <div className='bg-[url("https://cdn.cloudflare.steamstatic.com/steam/apps/990080/page_bg_generated_v6b.jpg?t=1661535551")]'></div>
    </div>
  )
}
