import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Steam Clone App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className='text-3x1 font-bold underline'>Hellow</h1>
    </div>
  )
}
